config/routes.rb
Rails.application.routes.draw do
  # resources :places

  resources :users, only: [:index] do
    resources :messages, only: [:index, :create, :new, :show, :destroy]
  end

  root 'sessions#new'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/checkin' => 'users#checkin'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :to_user, presence: true
  belongs_to :user, foreign_key: 'from_user'

end

app/models/messege.rb
class Messege < ActiveRecord::Base
  validates :to_user, presence: true
  belongs_to :user, foreign_key: 'from_user'

end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  validates_confirmation_of :password
  validates :name, :presence => true, :uniqueness => true
  before_save :encrypt_password
  has_many :messages, foreign_key: 'from_user', dependent: :delete_all

  def self.authenticate(name, password)
    user = User.find_by "name = ?", name
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def my_msgs
    Message.where("to_user = ?", self.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :destroy]

  def index
    @checkin = [session[:lat].to_f, session[:long].to_f]
    @inbox = []
    @outbox = []
    @has_read_history = []

    if current_user
      @inbox = Message.where("to_user = #{current_user.id}")
      @outbox = Message.where("from_user = #{current_user.id}")
      @hidden_msgs_count = Message.where("to_user = #{current_user.id} AND read='false'").length
      @has_read_history = Message.where("to_user = #{current_user.id} AND read='true'")
    end

    @close_msg = []
    @inbox.each do |coor|
      distance = Haversine.distance(@checkin, [coor.msg_lat, coor.msg_long]).to_miles
      if distance < 0.1
        coor.read = 'true'
        coor.save
        @close_msg.push(coor)
      end
    end
    
  end

  def show
    @message.read = true
    @message.save
  end

  def new
    @message = current_user.messages.new
  end

  def create
    @message = current_user.messages.new(message_params)
    if @message.save
      redirect_to user_messages_path, notice: 'Message successfully sent.'
    else
      render :new
    end
  end

  def destroy
    if current_user.id == @message.to_user
      @message.destroy
      redirect_to user_messages_path
    end
  end

  private
  def set_message
    @message = Message.find(params[:id])
  end

  def message_params
    params[:message][:read]=false
    params.require(:message).permit(:to_user, :body, :read, :msg_lat, :msg_long)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if current_user
      redirect_to user_messages_path(current_user)
    end
  end

  def create
    @user = User.authenticate(params[:name].capitalize, params[:password])

    if @user
      flash[:notice] = "Welcome #{@user.name}!"
      session[:user_id] = @user.id
      # home set to Epicodus lat/long
      session[:lat] = 45.520626
      session[:long] = -122.6795871
      redirect_to user_messages_path(current_user)
    else
      flash[:alert] = 'Unsuccessful login '
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    session[:lat] = nil
    session[:long] = nil
    flash[:notice] = "You've logged out "
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.name = @user.name.capitalize

    if @user.save
      flash[:notice] = 'Successful signup!'
      redirect_to '/'
    else
      flash[:alert] = 'There was a problem signing up'
      redirect_to '/signup'
    end

  end

  def index
    redirect_to '/'
  end

  def checkin
    session[:lat] = params[:message_msg_lat].to_d
    session[:long] = params[:message_msg_long].to_d
    redirect_to '/'
  end

private
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Message Hunter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyBmE8T1QkDeOjZxMhHU73L02DH-vJIvCG4' %>

    <%= yield(:head_tags) %>
  </head>

  <body>
    <nav class="navbar">
      <span class="navbar-brand mb-0 h1">Message Hunter</span>
        <% if current_user  %>
        <small>Checked in at :   <i class="fas fa-map-marker-alt"></i> <%= session[:lat] %>, <%= session[:long] %></small>

        <div class="float-right">
        <small> <%= current_user.name %> | <%= link_to "Sign out", '/signout' %> </small>
        <% else %>
        <small> Sign up | <%= link_to "Sign in", '/signin' %> </small>
      </div>
        <% end %>

    </nav>

    <div class="container-fluid">

      <div class="row">

        <% if flash[:alert] %>
          <div class="alert alert-danger alert-dismissible fade show flash_msg" role="alert">
            <%= flash[:alert] %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        <% end %>

        <% if flash[:notice] %>
          <div class="alert alert-success alert-dismissible fade show flash_msg" role="alert">
            <%= flash[:notice]  %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        <% end %>


        <div class="col-md-9 map-viewport" >
          <div id="map-all"></div>
          <div id="legend"></div>
        </div>

        <div class="col-md-3" id="ui">
          <%= yield %>
        </div>

      </div>


    </div>


  </body>
</html>

app/views/messages/_form.html.erb
<% provide :head_tags do %>
    <meta name='turbolinks-visit-control' content='reload'>
    <script>
        document.addEventListener("DOMContentLoaded", initMapAll);
    </script>
<% end %>
<%= form_for @message, url: {action: "create"} do |form| %>

<div class="row">
  <div class="col-md-6">

    <div class="form-group">
      <%= form.label :Latitude %>
      <%= form.text_field :msg_lat, class: "form-control", value: session[:lat] %>
    </div>

  </div>

  <div class="col-md-6">

    <div class="form-group">
      <%= form.label :Longitude %>
      <%= form.text_field :msg_long, class: "form-control", value: session[:long] %>
    </div>

  </div>
</div>


<div class="row">
  <div class="col-md-12">

      <div class="form-group">
        <%= form.label :Friends %>
        <%= form.select :to_user,
          options_for_select(User.where.not("id = #{current_user.id}").map {|u| [u.name.capitalize, u.id]}), {}, {class: 'form-control'} %>
      </div>

      <div class="form-group">
        <%= form.label :Message %>
        <%= form.text_area :body, class: "form-control", size: "24x6" %>
      </div>

      <div class="form-group">
        <%= form.submit 'Send Message', class: "btn btn-primary fancy-font", id: "send" %>
      </div>

  </div>
</div>

<% end %>

app/views/messages/index.html.erb
<% provide :head_tags do %>
<meta name='turbolinks-visit-control' content='reload'>
<script>
    document.addEventListener("DOMContentLoaded", initMapAll);
</script>
<% end %>

<div class="top_of_sidebar">

  <div class="checkin-box">
    <%= form_tag("/checkin", method: "get") do %>
    <%= hidden_field_tag(:message_msg_lat, '', value: session[:lat].to_f) %>
    <%= hidden_field_tag(:message_msg_long, '', value: session[:long].to_f) %>
    <%= submit_tag("Check In", class: "btn btn-secondary fancy-font") %>
    <% end %>
  </div>

  <div class="newmsg-box">
    <%= link_to 'New message', new_user_message_path, class: "btn btn-primary fancy-font" %>
  </div>

  <div class="card">
    <div class="card-body">
      <% message_found = @close_msg.length > 0 ? "You've unlocked a message!  🎉 🎉 🎉" : 'No messages for you here 😞' %>
      <h4 style="text-align: center;"><%= message_found %></h4>
    </div>
  </div>

  <% if @hidden_msgs_count > 0 %>
    <div class="unread_msgs_count">
      <button type="button" class="btn btn-primary">

        You have <span class="badge badge-light"><%= @hidden_msgs_count %></span> hidden <%= pluralize(@hidden_msgs_count, 'message').gsub(/\d\s/,'') %>
      </button>
    </div>
  <% end %>

</div>

<% if @has_read_history.length > 0 %>

  <div class="middle_of_sidebar">

    <h4>Found messages</h4>
    <div class="accordion" id="saved_messages">
      <% @has_read_history.each do |message| %>
      <div class="card">

        <div class="card-header" style="padding: 0;">
          <h5 class="mb-0">
            <%= link_to '', user_message_path(id: message), method: :delete, data: { confirm: 'Are you sure?' }, class: "fas fa-trash-alt float-right trash-pad"%>
            <button class="btn btn-link saved_messages" type="button" data-toggle="collapse" data-target="#collapse<%= message.id %>">
              From: <%= User.find(message.from_user.to_i).name.capitalize %>
            </button>
          </h5>
        </div>

        <div id="collapse<%= message.id %>" class="collapse" data-parent="#saved_messages">
          <div class="card-body">
            <small><%= message.body %></small>
          </div>
        </div>

      </div>
      <% end %>
    </div>

  </div>
<% end %>



<div class="hidden">
  <!-- these elements hidden for DOM querying needed for google maps integration -->
  <% @close_msg.each do |message| %>
    <p class="body"><%= message.body %></p>
    <p class="foundLat"><%= message.msg_lat %></p>
    <p class="foundLong"><%= message.msg_long %></p>
  <% end %>

  <div>
    <h4>Sent Messages</h4>
    <table>
      <thead>
        <tr>
          <th >To</th>
          <th ><i class="fas fa-map-marker-alt"></i></th>
        </tr>
      </thead>
      <tbody>
        <% @outbox.each do |message| %>
          <tr>
            <td><%= User.find(message.to_user.to_i).name.capitalize %></td>
            <td class="message_msg_lat" value="<%= message.msg_lat %>"><small><%= message.msg_lat %></small></td>
            <td class="message_msg_long" value="<%= message.msg_long %>"><small><%= message.msg_long %></small></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/messages/new.html.erb
<% provide :head_tags do %>
<meta name='turbolinks-visit-control' content='reload'>
<script>
    document.addEventListener("DOMContentLoaded", initMapAll);
</script>
<% end %>

<h3 class="fancy-font" style="font-size: 22px;">New Message</h3>

<%= render 'form', message: @message %>
<%= link_to '🔙', user_messages_path, class:"go-back" %>

app/views/messages/show.html.erb
<% provide :head_tags do %>
<meta name='turbolinks-visit-control' content='reload'>
<script>
    document.addEventListener("DOMContentLoaded", initMapAll);
</script>
<% end %>

<p>
  <strong>Created by:</strong>
  <%= User.find(@message.from_user.to_i).name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<%= link_to 'Back', user_messages_path %>

app/views/messeges/_form.html.erb
<%= form_for @messege, url: {action: "create"} do |form| %>
<div class="row">

  <div class="col-md-5">
      <div class="form-group">
        <%= form.label :Friends %>
        <%= form.select :to_user,
          options_for_select(User.where.not("id = #{current_user.id}").map {|u| [u.name.capitalize, u.id]}), {}, {class: 'form-control'} %>
      </div>

      <div class="form-group">
        <%= form.label :Messege %>
        <%= form.text_area :body, class: "form-control", size: "24x6" %>
      </div>

      <div class="form-group">
        <%= form.submit class: "btn btn-primary" %>
      </div>
  </div>

  <div class="col-md-2">
    <div class="form-group">
      <%= form.label :Latitude %>
      <%= form.text_field :msg_lat, class: "form-control", value: session[:lat] %>
    </div>

    <div class="form-group">
      <%= form.label :Longitude %>
      <%= form.text_field :msg_long, class: "form-control", value: session[:long] %>
    </div>

  </div>

</div>
<% end %>

app/views/places/index.html.erb
<% provide :head_tags do %>
    <meta name='turbolinks-visit-control' content='reload'>
    <script>
        document.addEventListener("DOMContentLoaded", initMapAll);
    </script>
<% end %>
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td class="place_latitude" value="<%= place.latitude %>"><%= place.latitude %></td>
        <td class="place_longitude" value="<%= place.longitude %>"><%= place.longitude %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>
<!-- 
<p>
  <div id="map-all"></div>
</p> -->

app/views/places/show.html.erb
<% provide :head_tags do %>
    <meta name='turbolinks-visit-control' content='reload'>
    <script>
    document.addEventListener("DOMContentLoaded", function(){
        initMap(<%=@place.latitude%>, <%=@place.longitude%>)
    });
    </script>
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @place.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @place.longitude %>
</p>


<p>
  <div id="map"></div>
</p>
<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-12">
    <%= form_for @user do |f| %>

    <div class="form-group">
      <%= f.label "Name" %>
      <%= f.text_field :name, class: "form-control" %>

    </div>

    <div class="form-group">
      <%= f.label "Password" %>
      <%= f.password_field :password, class: "form-control" %>

    </div>

    <div class="form-group">
      <%= f.label "Password confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

    </div>
    <%= f.submit "Sign up", class: "btn btn-primary"%>
    <% end %>

  </div>
</div>